blank_issues_enabled: false
contact_links:
  - name: 💬 Questions or Support
    url: https://github.com/preshalabs/presha.js/discussions
    about: Please ask and answer questions in GitHub Discussions
